config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :groups do
    resources :bookmarks
  end

  root 'groups#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def create
    @group = Group.find(params[:group_id])
    @bookmark = @group.bookmarks.create(bookmark_params)
    redirect_to group_path(@group)
  end

  def destroy
   @group = Group.find(params[:group_id])
   @bookmark = @group.bookmarks.find(params[:id])
   @bookmark.destroy
   redirect_to group_path(@group)
 end

  private
    def bookmark_params
      params.require(:bookmark).permit(:bmark)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    @group = Group.all
  end
  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def edit
    @group = Group.find(params[:id])
  end

  def create
    @group = Group.new(group_params)

    @group.save
    redirect_to @group
  end

  def update
    @group = Group.find(params[:id])

    @group.update(group_params)
    redirect_to @group

  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to groups_path
  end

  private
    def group_params
      params.require(:group).permit(:title)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/edit.html.erb
<h3>Edit Group <%= @group.title%></h3>

<%= form_with(model: @group) do |form| %>
  <p>
    <%= form.text_field :title, id:"edit_field_id" %>
  </p>
  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h3>Bookmarks</h3>

<table>
  <% @group.each do |group| %>
    <tr>
      <td><%= group.title %></td>

      <td><% group.bookmarks.each do |bookmark| %>
        <img src="http://<%= bookmark.bmark %>/favicon.ico" height="16" width="16">
        <a target="_blank" href="http://<%= bookmark.bmark %>"><%= bookmark.bmark %></a>
      <% end %></td>
      <td><%= link_to 'Show', group_path(group) %></td>
      <td><%= link_to 'Edit', edit_group_path(group), id: 'edit_group'%></td>
      <td><%= link_to 'Delete', group_path(group),
              method: :delete,
              data: { confirm: 'Are you sure?' },
              id: 'delete_group' %></td>
    </tr>

  <% end %>
</table>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<%= form_with scope: :group, url: groups_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<body id="bootstrap-overrides">
<p>
  <strong>Category:</strong>
  <%= @group.title %>
  <table>
</p>
<% @group.bookmarks.each do |bookmark| %>
<tr>

  <td>
    <img src="http://<%= bookmark.bmark %>/favicon.ico" height="16" width="16">
    <a target="_blank" href="http://<%= bookmark.bmark %>"><%= bookmark.bmark %></a></td>
  <td>
  <%= link_to 'Delete', [bookmark.group, bookmark],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
  </td>
  <p>
</tr>
<% end %>

</table>
<h3>Add a Bookmark to <%= @group.title%></h3>
<%= form_with(model: [ @group, @group.bookmarks.build ], local: true) do |form| %>
  <p>
    <%= form.text_field :bmark, id:"text_field_id" %>
    <p id="feedback"></p>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', groups_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookmarkManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>